spring:
  application:
    name: congii
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username:
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [Removed]
            client-secret: [Removed]
